---
apiVersion: v1
kind: Pod
metadata:
  name: redis-master
  labels:
    app: redis
spec:
  containers:
    - name: master
      image: redis
      env:
        - name: MASTER
          value: "true"
      ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Pod
metadata:
  name: k8-job-runner
  labels:
    app: k8-job-runner
spec:
  initContainers:
    - name: k8-job-seeder
      image: cptlemming/k8-job-seeder:1.0.0
  containers:
    - name: k8-job-runner
      image: cptlemming/k8-job-runner:1.0.1
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k8-job
spec:
  parallelism: 2
  template:
    metadata:
      name: k8-job
    spec:
      containers:
        - name: k8-worker
          image: cptlemming/k8-worker:1.0.3
      restartPolicy: OnFailure
